#!/bin/bash

# Ajouter tous les fichiers modifiés à l'index
git add .

# Effectuer un commit avec un message
read -p "Entrez votre message de commit : " message
git commit -m "$message"

# Pousser les modifications vers la branche actuelle
git push
